# Generated by Django 4.0.6 on 2022-09-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='Ferb', max_length=20)),
                ('lname', models.CharField(default='Fletcher', max_length=20)),
                ('email', models.CharField(default='ferb@gmail.com', max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('bdate', models.DateTimeField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('city', models.CharField(default='Tristate', max_length=20)),
                ('userType', models.CharField(max_length=20)),
                ('about', models.TextField(default='I love Farming')),
            ],
        ),
    ]
