# Generated by Django 4.0.6 on 2022-09-27 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0002_smuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='smuser',
            name='creatDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 14, 2, 18, 472369)),
        ),
        migrations.AddField(
            model_name='smuser',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 14, 2, 18, 472369)),
        ),
        migrations.AddField(
            model_name='smuserprofile',
            name='creatDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 14, 2, 18, 472369)),
        ),
        migrations.AddField(
            model_name='smuserprofile',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 14, 2, 18, 472369)),
        ),
    ]
