# Generated by Django 4.0.6 on 2022-09-27 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0003_smuser_creatdate_smuser_updatedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smuserprofile',
            name='user_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smuser',
            name='creatDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 14, 11, 35, 898684)),
        ),
        migrations.AlterField(
            model_name='smuser',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 14, 11, 35, 898684)),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='creatDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 14, 11, 35, 898684)),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 14, 11, 35, 898684)),
        ),
    ]
