# Generated by Django 4.0.6 on 2022-09-27 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0004_smuserprofile_user_id_alter_smuser_creatdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smuser',
            name='creatDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 14, 20, 40, 313013)),
        ),
        migrations.AlterField(
            model_name='smuser',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 14, 20, 40, 313013)),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='creatDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 14, 20, 40, 313013)),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 14, 20, 40, 313013)),
        ),
    ]
