# Generated by Django 4.0.6 on 2022-09-27 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0005_alter_smuser_creatdate_alter_smuser_updatedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smuser',
            name='creatDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 15, 36, 40, 738684)),
        ),
        migrations.AlterField(
            model_name='smuser',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='smuser',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 15, 36, 40, 738684)),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='bdate',
            field=models.DateTimeField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='creatDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 15, 36, 40, 738684)),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 15, 36, 40, 738684)),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='userType',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
