# Generated by Django 4.0.6 on 2022-09-27 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0006_alter_smuser_creatdate_alter_smuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smuserprofile',
            name='image',
            field=models.ImageField(default='', upload_to='profile/images'),
        ),
        migrations.AlterField(
            model_name='smuser',
            name='creatDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 20, 9, 16, 333117)),
        ),
        migrations.AlterField(
            model_name='smuser',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 20, 9, 16, 333117)),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='creatDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 20, 9, 16, 333117)),
        ),
        migrations.AlterField(
            model_name='smuserprofile',
            name='updateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 20, 9, 16, 333117)),
        ),
    ]
