# Generated by Django 4.0.6 on 2022-09-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0010_alter_smuser_creatdate_alter_smuser_updatedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smuserprofile',
            name='image',
            field=models.ImageField(default='irrigreatapp/images/defaultimg.png', upload_to='irrigreatapp/images'),
        ),
    ]
