# Generated by Django 4.0.6 on 2022-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0012_smuserprofile_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smuserprofile',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
