# Generated by Django 4.0.6 on 2022-09-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0013_alter_smuserprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='irrigreatapp/post')),
                ('creatDate', models.DateTimeField(blank=True)),
                ('updateDate', models.DateTimeField(blank=True)),
                ('likes', models.ManyToManyField(related_name='likes', to='irrigreatapp.smuser')),
            ],
        ),
    ]
