# Generated by Django 4.0.6 on 2022-10-05 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0016_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogger_id', models.CharField(max_length=20)),
                ('commenter_id', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('creatDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='irrigreatapp.post')),
            ],
        ),
    ]
