# Generated by Django 4.0.6 on 2022-10-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0018_alter_comment_blogger_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='irrigreatapp.comment'),
        ),
    ]
