# Generated by Django 4.0.6 on 2022-10-06 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0020_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blogger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloggers', to='irrigreatapp.smuserprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenters', to='irrigreatapp.smuserprofile'),
        ),
    ]
