# Generated by Django 4.0.6 on 2022-10-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0021_alter_comment_blogger_id_alter_comment_commenter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smuserprofile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smusers', to='irrigreatapp.smuser'),
        ),
    ]
