# Generated by Django 4.0.6 on 2022-10-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0024_alter_post_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='irrigreatapp.smuserprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blogger', to='irrigreatapp.smuserprofile'),
        ),
    ]
