# Generated by Django 4.0.6 on 2022-10-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0026_post_heading_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
