# Generated by Django 4.0.6 on 2022-10-20 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('irrigreatapp', '0033_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
